### ISSUE TITLE
Final Assignment - Peer Review - Neil

### ISSUE THREAD

**Issue by nbir012** [UOA-MEDSCI-736/BibianaLee-medsci736#11]
# Peer Review of Final Assignment

Hi Bibiana,
As requested, I've based this review on your document from your [forked repo](https://github.com/BibianaLee/BibianaLee-medsci736/blob/master/Assingments/medsci736-final-assignment-slee925-1.odt).
## What's great
- The abstract is a good start and I think with a brief summary of your introduction (see points below) you will have a very robust abstract.
- Your implementation and architecture section is logical and descriptive, I received a good understanding of the size of your data and filename structure
## What could be improved
- Start broad in your introduction, for example have a paragraph that outlines what cochlear inflammation is, how is data is collected/looks like and what techniques are currently used, if any, to analyse the data.
- Then start to narrow down on pros/cons of the current analyses, if any. Discuss your projectand how it aims to solve the issues you've outlined
- I quite like the intro of [this article](http://openresearchsoftware.metajnl.com/articles/10.5334/jors.120/) which I think presents the big picture through to little picture quite well. Hopefully it might help you as well. I always imagine an introduction to be like an upside down pyramid where you start with a really broad description and as you move down you get more refined/focused until you reach your thesis statement/problem.

Good luck and holla at me if you need any help.

Cheers,

Neil

**Comment by BibianaLee** [comment]
The article was quite handy thank you :) 
will update the assignment and upload it tomorrow

**Comment by BibianaLee** [comment]
Hey Neil, 

I've updated my final assignment using your suggestions and even added some diagrams :) 
Hope that's okay and if not just let me know 

Kind Regards, 
Bibiana

**Comment by nbir012** [comment]
Hi Bibiana,
That looks better
cheers,
Neil
