### ISSUE TITLE
Peer_Review_of_Final_Assignment_by_AAdam

### ISSUE THREAD

**Issue by Adamthe1st** [UOA-MEDSCI-736/BibianaLee-medsci736#12]
# Peer review of final assignment - by: Ahmed Adam

Hello Bibana, 
Great work you have done with your final assignment so far. Just a few comments:

*What I liked:
- I think your introduction was nicely put. You have mentioned what your data looks like and its main features (eg size, layout etc). I also think the length of the introduction was appropriate. well done :)
- The abstract is concise and nicely covers the main points of your project eg. overview, aim and what might the project be useful for. Excellent job!

*Possible improvements: 
- The title could be more specific. ie. hints what the software you are developing does with the data. Also you could mention which part of the inner ear you are statistically analyzing. 
- I liked the abstract. it gives a good overview of what the project is about. However, it would be great if you could indicate where the data was obtained from. 
- In your introduction: "Filenames contained a number followed by a 'D' for 'Day' and another number" I think this statement could be improved to define what the other number is.
- For the quality control I see that you have bullet pointed what you want to expand on. However maybe add test driven development we learned in class as well as a short explanation of what it means and how it works.
- For the operation system you have added Ubuntu which is great. However maybe try add which other operating systems are eligible to run your software eg mac/Windows. 

Overall, I think you are headed in the right direction Bibana. Good luck with the rest of the report and let me know if you would like me to further peer review your report prior to submission. 

Best wishes 
Ahmed.

**Comment by BibianaLee** [comment]
Thank you for your comments Ahmed 
I will update my assignment accordingly annnd upload it tomorrow :)

**Comment by BibianaLee** [comment]
Hey Ahmed,

I have edited my final assignment using your suggestions, please let me know if they're okay :) 
I couldn't really test on other operating systems so I just left it to unbuntu and put it down as a limitation on my read me 

Hope that's okay, 

Kind regards, 
Bibiana

**Comment by Adamthe1st** [comment]
Hello Bibana, you assignment document looks great. I am happy to close the issue now. 
Good luck with the rest of your exams :)
