### ISSUE TITLE
Feedback for Bibiana on the DMP

### ISSUE THREAD

**Issue by kdea020** [UOA-MEDSCI-736/BibianaLee-medsci736#2]
## What I liked:
- Your Responsibilities and Preservation sections are concise and clearly outline ownership, responsibility and procedure to ensure the survival of your data. Well done.
- Your file naming convention is clear and will definitely help you organise your data, and others understand it.
- Generally it seems like you've put some thought into how you're going to manage your data for project success.
## What could be improved:
- Good that you used the identifier (060603) for the field, but probably worth putting the name of the field in there as well.
- Fabiana suggested that the dates might be best as yyyy/mm/dd, for consistency with file naming conventions (where the computer will then sort files correctly by date). Up to you if you want to format the dates in your DMP similarly.
- It's actually the Faculty of Medical and Health Sciences (rather than the Department) :) This one's a bit nitpicky hahaha
- Under "Policies and Guidance", I like that you've linked to the policies that you'll be following, but you might like to describe how parts of these policies apply specifically to your project?
- Even if there are no ethics requirements, it could be useful to explain why this is so. For example, your data uses results from animal experiments - do you have a responsibility to check that this data was obtained ethically, and will be used ethically both by you now and for any future purpose?
- For file management, the DMP descriptor recommends you include details about the format and size. If you know what these are going to be at this stage, that would be valuable information for determining the full storage needs of the project, and how the data might be preserved.
- Under storage locations, it could be worth outlining a specific routine/location for backups, i.e. "Once weekly to a Google Drive folder under B. Lee's usernname, and to X Git repo."
- Under Metadata and Documentation... since this document is intended to be a comprehensive outline, where you have "outputs and etc." I'd suggest that you list in full what you are going to include in the readme file (if you know that at this early stage in the project).
- As you've indicated that the data is owned by a third party, you should fill out the section at the bottom of that list describing the details of the third-party ownership (i.e. who owns it and what your terms of use are).

**Comment by BibianaLee** [comment]
Hi Kieran, 

Thanks so much for your comprehensive review it was really helpful! 
I've tried editing my DMP according to the comments you gave me and you can view the new one here: 
https://github.com/BibianaLee/BibianaLee-medsci736/blob/d240f8a5db617c7a74879541101a2d5155d678f6/medsci736-DMP-slee925-v-1.docx

If you're happy with the edits please close the issue or you can give me extra comments if you want :) 

Kind Regards, 
Bibiana

**Comment by kdea020** [comment]
Hey Bibiana,

The new version looks great. Well done! 👍  Closing the issue :)
