### ISSUE TITLE
code_feedback 2016 04 10

### ISSUE THREAD

**Issue by Adamthe1st** [UOA-MEDSCI-736/BibianaLee-medsci736#5]
Hello Bibiana, 
Although I don't understand most of it (because of my coding level not that your code is bad), it looks like you proceeding fine with your code. I can see that you are annotating as you code which is great. However, just a quick tip: when you make a pull request, make sure to annotate your code in a way that makes it easier for someone else to follow. For example, when you define a function, you could annotate "creating a function to extract all data from file x"  this tells the reader exactly what are you trying to do and hence they might suggest helpful improvements. 

Keep up the good work 
Ahmed

**Comment by BibianaLee** [comment]
Hi Ahmed, 
Thank you for your feedback 
I have amended my script following your recommendations. Could you check them out at: 

https://github.com/UOA-MEDSCI-736/BibianaLee-medsci736/pull/8/commits/a6606d57e7990fe821ddbe8f50ef4ecc0585e1b0

If you're happy with the changes could you please close the issue or if something is still missing let me know :) 

Kind Regards, 
Bibiana

**Comment by Adamthe1st** [comment]
Dear Bibiana, 
I can now follow your code easily! and I will close the issue. 

Thank for getting in touch. Good luck with the rest of your code! Please let me know if you wanted me to peer rev future changes :)

Ahmed
