### ISSUE TITLE
13D4.py - peer review by Neil

### ISSUE THREAD

**Issue by nbir012** [UOA-MEDSCI-736/BibianaLee-medsci736#7]
Hi Bibiana,

*It looks good but there are a few things you could do to make it easier for someone who hasn't seen your code before.
*I would look at putting a comment at the top stating what the purpose of the file is as I don't have any context as to what the code is for.
*For loop on line 9, do you need to put the ''lines = [ ]'' above line 9? this way it would store all the lines in an array outside of the loop. I'm not an expert coder though so I don't know if this would work in your case.
*From line 15 to 28, I'm not sure what this does and based on your #wtf I suspect you are unsure also :-P
*I think the overall key thing to do is put a #blurb at the top of your code explaining what it is supposed to do - that would help me be able to try and understand the code.

Good luck (also I need to do the things I'm suggesting so I'm certainly no angel when it comes to practicing what I preach haha).

Cheers,

Neil

**Comment by BibianaLee** [comment]
Hi Neil, 
- I have amended my code following your feedback. I have added more comments to each line and have put a little blurb at the beginning of the file. 
- You're right about line 9 totally missed that! 
- I have removed lines 15 to 28  I was converting the numbers into numeric values but it was so long :| I still need to do something about this but I've removed it for now. 

You can check my changes at: https://github.com/UOA-MEDSCI-736/BibianaLee-medsci736/pull/8/commits/6a75b9200ce2bd713717c3390931f1113fbb5d3c

I hope that's everything and thank you for your feedback! If you're happy with the changes please close the issue and if I've missed something let me know

Kind Regards, 

Bibiana

**Comment by nbir012** [comment]
Looks good!

Good luck!
