### ISSUE TITLE
DMP-review

### ISSUE THREAD

**Issue by Luxo736** [UOA-MEDSCI-736/BibianaLee-medsci736#9]
Hi Bibiana:
 DMP review
-ORCid from Jerome: maybe able to be find in the main ORCid site.  Under his full name.
-I dont knowis there is  any etical issues with respect to guinea-pig ? Maybe  would be worth to explain it why it does not  have ethical issues to use guinea pigs
-Data is still beging  generated: does not say much,  will taht remain like that  until the end of the project?
-  Links : was that obatained  from articles or some other papers?
- Fo ownership  i think you could conatct  the  library they could give  you some assiatncy  with that
- Sources to deliver your plan :   maybe  you would  discrebe the “personnel” way to completion.
  Good job! let me know if you need extra explanation about  my  comments.
  Hugs
  Luis-Miguel

**Comment by Luxo736** [comment]
Hi Bibiana:

Hope you could let  me know  when you made the changes  then I will check and if I get satisfy i will be able to close the issue do not forget we have it  only today.

Hugs.

Lucho

**Comment by BibianaLee** [comment]
Hi Luis :) 

Thanks so much for your review I have edited my DMP according to the feedback you gave me an you can view it here: https://github.com/BibianaLee/BibianaLee-medsci736/blob/d240f8a5db617c7a74879541101a2d5155d678f6/medsci736-DMP-slee925-v-1.docx

If you feel like that's good enough please close the issue or let me know what more I can change 

Kind Regards,
Bibiana

**Comment by Luxo736** [comment]
all good!
 awesome job!

i hope you will progressing

Luis.
